<<<<<<< HEAD
'use client';

export default function Layout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
=======
import type { Metadata } from 'next';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Script
          type="text/javascript"
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_ID}`}
          strategy="beforeInteractive" 
        />
        {children}
      </body>
    </html>
  );
>>>>>>> b45f8e3 (feat:지도연결)
}
