export const response = {
  data: {
    content: [
      {
        addressName: '서울 송파구 잠실동 295-10', // 지번 주소 기준으로 응답
        addressType: 'REGION_ADDR', // '지번 주소' 코드
        regionAddress: {
          addressName: '서울 송파구 잠실동 295-10',
          region1depthName: '서울',
          region2depthName: '송파구',
          region3depthHName: '잠실본동',
          region3depthName: '잠실동',
          mainAddressNo: '295',
          subAddressNo: '10',
        },
        roadAddress: {
          addressName: '서울 송파구 도곡로64길 7-22',
          region1depthName: '서울',
          region2depthName: '송파구',
          region3depthName: '잠실동',
          roadName: '도곡로64길',
          mainBuildingNo: '7',
          subBuildingNo: '22',
          buildingName: '푸른채',
        },
      },
      {
        addressName: '서울 강남구 역삼동 123-45',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 강남구 역삼동 123-45',
          region1depthName: '서울',
          region2depthName: '강남구',
          region3depthHName: '역삼1동',
          region3depthName: '역삼동',
          mainAddressNo: '123',
          subAddressNo: '45',
        },
        roadAddress: {
          addressName: '서울 강남구 테헤란로 10',
          region1depthName: '서울',
          region2depthName: '강남구',
          region3depthName: '역삼동',
          roadName: '테헤란로',
          mainBuildingNo: '10',
          subBuildingNo: '',
          buildingName: '삼성타운',
        },
      },
      {
        addressName: '서울 마포구 합정동 1-1',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 마포구 합정동 1-1',
          region1depthName: '서울',
          region2depthName: '마포구',
          region3depthHName: '합정동',
          region3depthName: '합정동',
          mainAddressNo: '1',
          subAddressNo: '1',
        },
        roadAddress: {
          addressName: '서울 마포구 양화로 50',
          region1depthName: '서울',
          region2depthName: '마포구',
          region3depthName: '합정동',
          roadName: '양화로',
          mainBuildingNo: '50',
          subBuildingNo: '',
          buildingName: '합정빌딩',
        },
      },
      {
        addressName: '서울 중구 명동 123-4',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 중구 명동 123-4',
          region1depthName: '서울',
          region2depthName: '중구',
          region3depthHName: '명동',
          region3depthName: '명동',
          mainAddressNo: '123',
          subAddressNo: '4',
        },
        roadAddress: {
          addressName: '서울 중구 명동길 10',
          region1depthName: '서울',
          region2depthName: '중구',
          region3depthName: '명동',
          roadName: '명동길',
          mainBuildingNo: '10',
          subBuildingNo: '',
          buildingName: '명동타워',
        },
      },
      {
        addressName: '서울 서초구 서초동 456-78',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 서초구 서초동 456-78',
          region1depthName: '서울',
          region2depthName: '서초구',
          region3depthHName: '서초1동',
          region3depthName: '서초동',
          mainAddressNo: '456',
          subAddressNo: '78',
        },
        roadAddress: {
          addressName: '서울 서초구 서초대로 20',
          region1depthName: '서울',
          region2depthName: '서초구',
          region3depthName: '서초동',
          roadName: '서초대로',
          mainBuildingNo: '20',
          subBuildingNo: '',
          buildingName: '서초빌딩',
        },
      },
      {
        addressName: '서울 강서구 화곡동 123-12',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 강서구 화곡동 123-12',
          region1depthName: '서울',
          region2depthName: '강서구',
          region3depthHName: '화곡본동',
          region3depthName: '화곡동',
          mainAddressNo: '123',
          subAddressNo: '12',
        },
        roadAddress: {
          addressName: '서울 강서구 강서로 100',
          region1depthName: '서울',
          region2depthName: '강서구',
          region3depthName: '화곡동',
          roadName: '강서로',
          mainBuildingNo: '100',
          subBuildingNo: '',
          buildingName: '강서빌딩',
        },
      },
      {
        addressName: '서울 동작구 사당동 456-1',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 동작구 사당동 456-1',
          region1depthName: '서울',
          region2depthName: '동작구',
          region3depthHName: '사당1동',
          region3depthName: '사당동',
          mainAddressNo: '456',
          subAddressNo: '1',
        },
        roadAddress: {
          addressName: '서울 동작구 동작대로 200',
          region1depthName: '서울',
          region2depthName: '동작구',
          region3depthName: '사당동',
          roadName: '동작대로',
          mainBuildingNo: '200',
          subBuildingNo: '',
          buildingName: '동작빌딩',
        },
      },
      {
        addressName: '서울 은평구 불광동 789-10',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 은평구 불광동 789-10',
          region1depthName: '서울',
          region2depthName: '은평구',
          region3depthHName: '불광동',
          region3depthName: '불광동',
          mainAddressNo: '789',
          subAddressNo: '10',
        },
        roadAddress: {
          addressName: '서울 은평구 통일로 300',
          region1depthName: '서울',
          region2depthName: '은평구',
          region3depthName: '불광동',
          roadName: '통일로',
          mainBuildingNo: '300',
          subBuildingNo: '',
          buildingName: '은평빌딩',
        },
      },
      {
        addressName: '서울 강북구 수유동 987-6',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 강북구 수유동 987-6',
          region1depthName: '서울',
          region2depthName: '강북구',
          region3depthHName: '수유1동',
          region3depthName: '수유동',
          mainAddressNo: '987',
          subAddressNo: '6',
        },
        roadAddress: {
          addressName: '서울 강북구 도봉로 400',
          region1depthName: '서울',
          region2depthName: '강북구',
          region3depthName: '수유동',
          roadName: '도봉로',
          mainBuildingNo: '400',
          subBuildingNo: '',
          buildingName: '강북타워',
        },
      },
      {
        addressName: '서울 구로구 구로동 123-45',
        addressType: 'REGION_ADDR',
        regionAddress: {
          addressName: '서울 구로구 구로동 123-45',
          region1depthName: '서울',
          region2depthName: '구로구',
          region3depthHName: '구로동',
          region3depthName: '구로동',
          mainAddressNo: '123',
          subAddressNo: '45',
        },
        roadAddress: {
          addressName: '서울 구로구 디지털로 10',
          region1depthName: '서울',
          region2depthName: '구로구',
          region3depthName: '구로동',
          roadName: '디지털로',
          mainBuildingNo: '10',
          subBuildingNo: '',
          buildingName: '구로디지털타워',
        },
      },
    ],
    pagination: {
      pageNumber: 0,
      pageSize: 10,
      totalPages: 3,
      totalElements: 30,
      hasNext: true,
    },
  },
};
