export const CARD_INSTITUTIONS = [
  { label: '기업 BC', value: 'IBK_BC' },
  { label: '광주은행', value: 'GWANGJUBANK' },
  { label: '롯데카드', value: 'LOTTE' },
  { label: 'KDB산업은행', value: 'KDBBANK' },
  { label: 'BC카드', value: 'BC' },
  { label: '삼성카드', value: 'SAMSUNG' },
  { label: '새마을금고', value: 'SAEMAUL' },
  { label: '신한카드', value: 'SHINHAN' },
  { label: '신협', value: 'SHINHYEOP' },
  { label: '씨티카드', value: 'CITI' },
  { label: '우리카드', value: 'WOORI' },
  { label: '우체국예금보험', value: 'POST' },
  { label: '저축은행중앙회', value: 'SAVINGBANK' },
  { label: '전북은행', value: 'JEONBUKBANK' },
  { label: '제주은행', value: 'JEJUBANK' },
  { label: '카카오뱅크', value: 'KAKAOBANK' },
  { label: '케이뱅크', value: 'KBANK' },
  { label: '토스뱅크', value: 'TOSSBANK' },
  { label: '하나카드', value: 'HANA' },
  { label: '현대카드', value: 'HYUNDAI' },
  { label: 'KB국민카드', value: 'KOOKMIN' },
  { label: 'NH농협카드', value: 'NONGHYEOP' },
  { label: 'Sh수협은행', value: 'SUHYEOP' },
  { label: '페이코', value: 'PCP' },
  { label: 'KB증권', value: 'KBS' },
] as const;
